language: node_js
node_js:
- 6
- 4
before_script:
- npm prune
script:
- npm run test
after_success:
- npm run ci:coveralls
before_deploy:
- npm run build
deploy:
  provider: npm
  on:
    repo: wikiwi/react-jss-theme
    tags: true
    node: 4
  skip_cleanup: true
  email: vinh@wikiwi.io
  api_key:
    secure: xn9kLosYckI0zMa7h6UTtg8YzkL/s/YDsXkesJnidKFnSSDtnelbOmTEyMPl1/SDKBzA7xtwExxpx7mzCBP6QEkUJu3VAgRQivqo+AxQsCwxbxfLS0WTgSl3ymseGTRMTuB9btLrm8g1SXQ849EIcZK4uzvhDutJ0aAAX7vzOEBKnTcT58GEL2j+ngZ0C4ZEYRgXF7mA5fQ7oAXMy3XNW2KA/GbJLLch0othO7niQ3MADo5N7XrSF6UX2IZxBlrWBIrTu/mdTur8FHudApKo8F7STMVFugixdH1/SuQIskXt/dqHb6tqY2coluvZM+u5+BdDIE0PCsejTx1mZOW+3+f9p9+Nsc2tPZyYpss6Eyxz87Vtq0KYmarPb+b0lef0tdMrEjx7bQfiIg7I9RMQ1oTKm5y66i/EdCp33mriY7A8t/t+qo6fVc0x45WMCRXIq6jRZ3Ko5Ytp91U//kRyLhg8SKtbRDwRdFT761A/TSD1h5H+XTpPub25vNBn3AFcYjg8jq+onlcNl4Y7jiGuqORVTM11SOqpXxLCC/BpyHioz7nlkD0YY2bhHQToJOgc/RDrstg+aXAMdZ3SPtWvvEyBhcUpwhAlAOduXIlgX3WWNTG2L++Q+mtawO6KmO9bS5TgvTJpehAVaUPehDQz4t8hTsforBLGpkJg5cgukPM=
